spring:
  application:
    name: m3-loan-application-service.yaml
  datasource:
    url: jdbc:mysql://db-m1:3306/m1db?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
