apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1-credit-simulation-service-deployment
  labels:
    app: m1-credit-simulation-service-deployment
spec:
  selector:
    matchLabels:
      app: m1-credit-simulation-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: m1-credit-simulation-service-deployment
    spec:
      containers:
        - name: m1-credit-simulation-service
          image: dockerhub_user/m1-credit-simulation-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_M1
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_M1
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_M1
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_M1
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_M1
---
apiVersion: v1
kind: Service
metadata:
  name: m1-credit-simulation-service
  labels:
    app: m1-credit-simulation-service
spec:
  selector:
    app: m1-credit-simulation-service-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
