apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1-credit-simulation-service-deployment
  labels:
    app: m1-credit-simulation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m1-credit-simulation-service
  template:
    metadata:
      labels:
        app: m1-credit-simulation-service
    spec:
      containers:
        - name: m1-credit-simulation-service
          image: xsh1ft/m1-credit-simulation-service:1.0
          ports:
            - containerPort: 8080
          env:
            # Variables desde ConfigMap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_M1

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_M1

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_M1

            # Variables desde Secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_M1
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_M1

            # Configuración del Config Server y Eureka
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server-service:8888"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: m1-credit-simulation-service
  labels:
    app: m1-credit-simulation-service
spec:
  selector:
    app: m1-credit-simulation-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
