apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  DB_USER_M1: cm9vdA== # Base64 encoded "root"
  DB_PASSWORD_M1: cGFzc3dvcmQ= # Base64 encoded "password"

  DB_USER_M2: cm9vdA== # Base64 encoded "root"
  DB_PASSWORD_M2: cGFzc3dvcmQ= # Base64 encoded "password"

